version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * */3 *"
    target-branch: "automatic-version-bumps"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 * */3 *"
    target-branch: "automatic-version-bumps"
